name: Update Readme ascii graph and workflow with random cron interval
on:
  push:
    branches: [main]
    paths-ignore:
      - .github/workflows/rating-chart.yml
      - .github/workflows/main.yml
      - .github/templates/
  schedule:
    - cron: "0 */12 * * *"
jobs:
  ratings-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          token: ${{ secrets.GH_TOKEN_1 }}
        name: Setup Python

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
        name: Install dependencies

      - run: pip install -r code/requirements.txt
        name: Create Chart

      - run: |
          python code/rating_chart.py > chart.txt
          CHART=$(cat chart.txt)
          echo "::set-output name=chart::$CHART"
      - run: |
          currentDate=`env TZ=Turkey date`
          sed -i "/# ♟︎ Chess.com Ratings Chart #/ { N; /Chart last updated/c\# ♟︎ Chess.com Ratings Chart #\n\nRapid Rating\n\n$CHART\n\nChart last updated - ${currentDate}\n\n}" README.md
        name: Update README
      - run: |
          python code/generate_random_workflow.py > rating-yaml.txt
          YAML=$(cat rating-yaml.txt)
          echo "::set-output name=yaml::$YAML"
      - run: cat rating-yaml.txt > .github/workflows/rating-chart.yml
      - id: changed
        run: git diff --exit-code
        continue-on-error: true
        name: Commit changes
      - if: ${{ steps.changed.outcome == 'failure' }}
        uses: EndBug/add-and-commit@v4
        with:
          author_name: "[Bot] NotAShelf"
          author_email: "62766066+notashelf@users.noreply.github.com"
          message: "update README and workflow timing"
          add: "README.md .github/workflows/rating-chart.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_1 }}
