name: Update Readme ascii graph and workflow with random cron interval
on:
  push:
    branches: [main]
    paths-ignore:
      - .github/workflows/rating-chart.yml
      - .github/workflows/main.yml
      - .github/templates/
      - README.md
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  ratings-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN_1 }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install -r code/requirements.txt

      - name: Create Chart
        run: |
          python code/rating_chart.py > chart.txt
          CHART=$(cat chart.txt)
          echo "::set-output name=chart::$CHART"

      - run: cat assets/README-1.md > README.md
      - run: cat chart.txt >> README.md

      - run: |
          currentDate=`env TZ=Europe/Istanbul date`
          printf "\nChart last updated - ${currentDate}" >> README.md

      - run: cat assets/README-2.md >> README.md
        name: Update workflow yaml file

      - run: |
          python code/generate_random_workflow.py > rating-yaml.txt
          YAML=$(cat rating-yaml.txt)
          echo "::set-output name=yaml::$YAML"

      - name: Insert rating chart
        run: cat rating-yaml.txt > .github/workflows/rating-chart.yml

      - name: Commit changes
        id: changed
        run: git diff --exit-code
        continue-on-error: true

      - if: ${{ steps.changed.outcome == 'failure' }}
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "[Bot] NotAShelf"
          author_email: raf@notashelf.dev
          message: "update README rating chart & workflow timings"
          add: "README.md .github/workflows/rating-chart.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_1 }}
