name: "Automatic updates of profile statistics"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore:
      - .github/workflows/rating-chart.yml
      - .github/workflows/main.yml
      - .github/templates/
      - README.md
  schedule:
    - cron: "0 */12 * * *"

jobs:
  ratings-chart:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN_1 }}

      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: "Install Requirements"
        run: pip install -r src/requirements.txt

      # Step 1: Update the blog posts section with the *last 5* posts that I've written
      # using the blog's RSS feed.
      - name: "Update Blog Posts"
        run: python src/fetch_blog_feed.py templates/README-1.md

      # Step 2: Update the projects table using the gen_table script. It takes a json file
      # containing my projects, and creates a markdown table. We then substitute that table
      # in README-1.md, replacing the '{{ TABLE_PLACEHOLDER }}' template literal.
      - name: "Generate Projects Table"
        run: |
          table_content=$(python src/gen_table.py templates/projects.json | sed 's/\\/\\\\n/g')
          awk -v content="$table_content" '{gsub("{{ TABLE_PLACEHOLDER }}", content)}1' templates/README-1.md > temp.md && mv temp.md templates/README-1.md

          # For debugging
          echo "$table_content"
          cat templates/README-1.md

      # Step 3: Update my chess ratings graph. It (poorly) wraps chess.com API to get
      # my statistics and create a very simple ASCII graph. It is then substituted in
      # README-1.md, replacing the '{{ RATINGS_PLACEHOLDER }}' template literal.
      - name: "Update Chess Statistics"
        run: |
          chart_content=$(python src/rating_chart.py | sed 's/\\/\\\\n/g')
          awk -v content="$chart_content" '{gsub("{{ RATINGS_PLACEHOLDER }}", content)}1' templates/README-1.md > temp.md && mv temp.md templates/README-1.md

          # For debugging
          echo "$chart_content"
          cat templates/README-1.md

      # Step 4: Update the "last updated" date below the chart. This could've been put
      # in the Python script, but this works and I ain't fixing that.
      - name: "Update last update date"
        run: |
          sed -i "s/{{ LAST_UPDATED }}/$(date +'%Y-%m-%d')/" templates/README-1.md

      # Okay we're done modifying the template, now it can be copied to the repository root
      # as README.md. This is a weird approach, but since README-1md is never going to be
      # committed, it can be left as is after the modifications.
      - name: "Move templates/README-1.md to README.md"
        run: cat templates/README-1.md > README.md

      - name: "Update workflow recipe"
        run: |
          python src/gen_random_workflow.py > rating-yaml.txt
          YAML=$(cat rating-yaml.txt)
          echo "::set-output name=yaml::$YAML"

      - name: "Insert rating chart"
        run: cat rating-yaml.txt > .github/workflows/rating-chart.yml

      - name: "Commit changes"
        id: changed
        run: git diff --exit-code
        continue-on-error: true

      - name: "Add and commit changes"
        if: ${{ steps.changed.outcome == 'failure' }}
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "[Bot] NotAShelf"
          author_email: "raf@notashelf.dev"
          add: "README.md .github/workflows/rating-chart.yml"
          message: "ci: update README with new statistics"

        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_1 }}
